package postgres

import (
	"context"
	"fmt"

	"github.com/celio001/backend-challenge-go/internal/domain/wallet"
)

type LedgerRepository struct {
	db execer
}

func NewLedgerRepository(db execer) *LedgerRepository {
	return &LedgerRepository{db: db}
}

// The entry id is generated by the database: the domain entry has no identity of its own.
func (r *LedgerRepository) Append(ctx context.Context, e wallet.LedgerEntry) error {
	_, err := r.db.Exec(ctx,
		`INSERT INTO wallet_ledger_entries
		   (id, wallet_id, transaction_id, wallet_version, direction, amount_minor, currency,
		    balance_before_minor, balance_after_minor, created_at)
		 VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7, $8, $9)`,
		string(e.WalletID()), string(e.TxID()), e.WalletVersion(), string(e.Direction()),
		e.Amount().Minor(), string(e.Amount().Currency()),
		e.BalanceBefore().Minor(), e.BalanceAfter().Minor(), e.CreatedAt())
	if err != nil {
		return fmt.Errorf("insert ledger entry: %w", err)
	}
	return nil
}
